### ISSUE TITLE
编译失败，想请问一下

### ISSUE THREAD

**Issue by chunyi1994** [chronolaw/ngx_cpp_dev#2]
你好， 
你在这个文件ngx_cpp_dev/http/test/NdgTestHandler.hpp 中有大量的std::cout来测试输出，
但是凭着直觉，一个ngx_str_t应该是不能直接std::cout<<ngx_str 这样用的吧？

在编译的时候确实遇到了这样的问题，编译错误。
std::cout << NgxDatetime::today() << std::endl;   //就是这一行报错了。

**把所有的cout都注释掉，编译就成功了。**

请问我是哪里没有配置好才会这样的吗？
虽然只是cout，无伤大雅，但很好奇为什么作者这样写没有问题。
望解答，谢谢Chrono。

**Comment by sukiand** [comment]
在ngxpp/NgxString.hpp里，已经重载了<< 
NgxString, ngx_str_t 都重载了，应该是支持直接std::cout<<ngx_str_t的
