### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by dede8385** [chronolaw/ngx_cpp_dev#3]
环境：CentOS7 
Boost：1.60
错误提示如下：（我只编译http/test模板）

g++ -c -g -O0 -std=c++11 -Wall  -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /home/developer/ngx_cpp_dev/ngxpp -I src/stream \
        -o objs/addon/test/ModNdgTest.o \
        /home/developer/ngx_cpp_dev/http/test/ModNdgTest.cpp
In file included from /usr/local/include/boost/optional/optional.hpp:49:0,
                 from /usr/local/include/boost/optional.hpp:15,
                 from /usr/local/include/boost/format/internals.hpp:20,
                 from /usr/local/include/boost/format.hpp:38,
                 from /home/developer/ngx_cpp_dev/ngxpp/NgxVariable.hpp:6,
                 from /home/developer/ngx_cpp_dev/ngxpp/NgxAll.hpp:32,
                 from /home/developer/ngx_cpp_dev/http/test/NdgTestConf.hpp:6,
                 from /home/developer/ngx_cpp_dev/http/test/NdgTestInit.hpp:6,
                 from /home/developer/ngx_cpp_dev/http/test/ModNdgTest.cpp:3:
/usr/local/include/boost/detail/reference_content.hpp:74:24: error: expected type-specifier before ‘mpl’
 template <typename T = mpl::void_> struct make_reference_content;
                        ^
/usr/local/include/boost/detail/reference_content.hpp:74:24: error: expected ‘>’ before ‘mpl’
/usr/local/include/boost/detail/reference_content.hpp:91:32: error: ‘mpl’ was not declared in this scope
 struct make_reference_content< mpl::void_ >
                                ^
......

**Comment by chronolaw** [comment]
目前正在更新这些工具类，请稍等一段时间再用。

**Comment by chronolaw** [comment]
或者查看commit历史，用三月份之前的版本。
